version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb

    ports:
      - "3306:3306"

  laravel:
    build:
      context: ./back-end

    container_name: laravel

    ports:
      - "8000:80"

    depends_on:
      - mysql

    volumes:
      - ./back-end:/var/www/html

    working_dir:  /var/www/html

  #reverb:
  #  build:
  #    context: ./back-end
  #  container_name: reverb
  #  command: php artisan reverb:start --host=0.0.0.0 --port=9000
  #  ports:
  #    - "9000:9000"
  #  depends_on:
  #    - laravel
  #  volumes:
  #    - ./back-end:/var/www/html
  #  working_dir: /var/www/html

  react:
    build:
      context: ./front-end

    container_name: react

    ports:
      - "5173:5173"

    volumes:
      - ./front-end:/app
      - /app/node_modules

    working_dir: /app

    command: npm run dev -- --host 0.0.0.0

    stdin_open: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql